# Configurações do Site
title: "Pautas Socioeducativas"
description: "Acompanhe as pautas legislativas para a categoria de Agentes de Segurança Socioeducativos."
baseurl: "/pautas-socioeducativas"
url: "https://juliocjd.github.io" # URL do seu site no GitHub Pages

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclusões
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
