# Configurações do Site
title: "Pautas Socioeducativas"
description: "Acompanhe as pautas legislativas para a categoria de Agentes de Segurança Socioeducativos."

# CORREÇÃO 1: O site agora está na raiz do domínio Vercel
baseurl: "" 

# CORREÇÃO 2: A URL oficial agora é a do Vercel
url: "https://pautas-socioeducativas.vercel.app" 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Configuração de Coleções
collections:
  pautas:
    output: true
    permalink: /:collection/:name/

# Exclusões
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
  - README.md
