backend:
  name: github
  repo: juliocjd/pautas-socioeducativas
  branch: main
  site_domain: bucolic-dodol-77b24b.netlify.app
  site_url: https://juliocjd.github.io/pautas-socioeducativas

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: 'pautas'
    label: 'Pautas'
    folder: '_pautas'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'text' }
      - { label: 'Casa Legislativa', name: 'casa', widget: 'select', options: ['Câmara dos Deputados', 'Senado Federal'] }
      - { label: 'Status', name: 'status', widget: 'string' }
      - { label: 'Corpo da Página', name: 'body', widget: 'markdown' }
