backend:
  name: github
  repo: juliocjd/pautas-socioeducativas
  branch: main
  # CORREÇÃO 1: O site_domain já estava certo, mas vamos garantir
  site_domain: bucolic-dodol-77b24b.netlify.app
  # CORREÇÃO 2: O site_url agora é o do Netlify!
  site_url: https://bucolic-dodol-77b24b.netlify.app

# CORREÇÃO 3: No Netlify, o site está na raiz, não em um subdiretório
media_folder: assets/images
public_folder: /assets/images

collections:
  - name: pautas
    label: Pautas
    folder: _pautas
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Descrição, name: description, widget: text }
      - { label: 'Casa Legislativa', name: casa, widget: select, options: ['Câmara dos Deputados', 'Senado Federal'] }
      - { label: Status, name: status, widget: string }
      - { label: 'Corpo da Página', name: body, widget: markdown }
