backend:
  name: github
  repo: juliocjd/pautas-socioeducativas
  branch: main
  # CORREÇÃO 1: O site_domain agora é o do Vercel
  site_domain: pautas-socioeducativas-psi.vercel.app # SUBSTITUA PELA SUA URL
  # CORREÇÃO 2: O site_url também aponta para o Vercel
  site_url: https://juliocjd.github.io/pautas-socioeducativas # MANTENHA ESTE PARA OS LINKS DO SITE

# CORREÇÃO 3: Como o site final tem um baseurl, o public_folder deve refletir isso
media_folder: assets/images
public_folder: /pautas-socioeducativas/assets/images

collections:
  - name: pautas
    label: Pautas
    folder: _pautas
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Descrição, name: description, widget: text }
      - { label: 'Casa Legislativa', name: casa, widget: select, options: ['Câmara dos Deputados', 'Senado Federal'] }
      - { label: Status, name: status, widget: string }
      - { label: Pauta Principal, name: featured, widget: boolean, default: false }
      - { label: 'Votação em Plenário?', name: is_plenary_vote, widget: boolean, default: false }
      - label: "Membros-Chave desta Pauta"
        name: "key_players"
        widget: "list"
        fields:
          - { label: "ID do Parlamentar", name: "id", widget: "select", options: [{% for parl in site.data.parlamentares_base %}{{ parl.id }},{% endfor %}] }
          - { label: "Papel/Função", name: "role", widget: "string" }
      - { label: 'Corpo da Página', name: body, widget: markdown }
