backend:
  name: github
  repo: juliocjd/pautas-socioeducativas
  branch: main
  site_domain: bucolic-dodol-77b24b.netlify.app
  site_url: https://juliocjd.github.io/pautas-socioeducativas
media_folder: assets/images
public_folder: /pautas-socioeducativas/assets/images
collections:
  - name: pautas
    label: Pautas
    folder: _pautas
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Descrição, name: description, widget: text }
      - { label: 'Casa Legislativa', name: casa, widget: select, options: ['Câmara dos Deputados', 'Senado Federal'] }
      - { label: Status, name: status, widget: string }
      - { label: Pauta Principal, name: featured, widget: boolean, default: false }
      # NOVO CAMPO ABAIXO
      - { label: 'Votação em Plenário?', name: is_plenary_vote, widget: boolean, default: false, hint: "Marque 'Sim' se a votação for por todos os deputados. 'Não' se for uma comissão ou grupo específico." }
      - label: "Membros-Chave desta Pauta"
        name: "key_players"
        widget: "list"
        fields:
          - { label: "ID do Parlamentar", name: "id", widget: "select", options: [{% for parl in site.data.parlamentares_base %}{{ parl.id }},{% endfor %}] }
          - { label: "Papel/Função", name: "role", widget: "string", hint: "Ex: Relator, Presidente da Comissão, Membro" }
      - { label: 'Corpo da Página', name: body, widget: markdown }
