# Nome do workflow
name: Build and Deploy Jekyll Site

# Dispara o workflow quando há um push para a branch 'main'
on:
  push:
    branches:
      - main
  # Permite executar manualmente na aba Actions
  workflow_dispatch:

# Permissões necessárias para o workflow
permissions:
  contents: read
  pages: write
  id-token: write

# Define os jobs que serão executados
jobs:
  # Job para construir o site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Versão compatível com o github-pages
          bundler-cache: true # Usa cache para acelerar o build
      - name: Install dependencies and build site
        run: |
          bundle install
          bundle exec jekyll build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # Job para publicar o site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Depende do job 'build' terminar com sucesso
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
